# Generated by Django 3.1 on 2020-12-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_leaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='leaf',
            field=models.CharField(max_length=300),
        ),
    ]
