# Generated by Django 3.1 on 2020-12-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201228_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
