# Generated by Django 3.1 on 2020-12-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201228_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
