# Generated by Django 3.1 on 2020-12-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='totalPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='totalPrice',
            field=models.FloatField(default=0),
        ),
    ]
