# Generated by Django 3.1 on 2020-12-31 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201228_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
