# Generated by Django 3.1 on 2021-01-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
