# Generated by Django 3.1 on 2021-01-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210129_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
