# Generated by Django 3.1 on 2021-02-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210201_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laptopFeatures',
            new_name='LaptopFeature',
        ),
    ]
