# Generated by Django 3.1 on 2021-02-02 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210202_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
