# Generated by Django 3.1 on 2021-02-03 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210202_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('ram', models.FloatField()),
                ('screenSize', models.FloatField()),
                ('storage', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
