# Generated by Django 3.1 on 2021-02-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_desktopfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStorageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('hardwareInterface', models.CharField(max_length=80)),
                ('portable', models.CharField(max_length=5)),
                ('storage', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
