# Generated by Django 3.1 on 2020-12-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
