# Generated by Django 3.1 on 2020-12-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201227_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name2',
            new_name='name',
        ),
    ]
