# Generated by Django 3.1 on 2020-12-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20201227_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
